name: cakeday_reminder
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  dio: ^5.4.1
  floor: ^1.4.2
  floor_generator: ^1.4.2
  get_it: ^7.6.7
  excel: ^4.0.2
  file_picker: ^6.2.0
  collection: ^1.18.0
  flutter_launcher_icons: ^0.13.1
  simple_gradient_text: ^1.3.0
  animate_gradient: ^0.0.2+1
  flutter_gradient_animation_text: ^1.0.2
  glowy_borders: ^1.0.2
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: 'assets/images/app_icon.png'
  android: true
  ios: true
  remove_alpha_ios: true

flutter_native_splash:
  color: "#718974"
  image: assets/images/splash_screen_image.png
  android_12:
    color: "#718974"
    image: assets/images/app_icon.png

